spring.application.name=pictoglyphapi

spring.datasource.url=jdbc:postgresql://localhost:5432/pictoglyph
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

pictoglyph.seed.enabled=true
pictoglyph.ml.base-url=http://localhost:8001
